version: '3.8'

services:
  # Express API Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared
    networks:
      - health-wellness-network

  # Streamlit Frontend
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:5000/api
    depends_on:
      - api
    networks:
      - health-wellness-network

networks:
  health-wellness-network:
    driver: bridge 